const btnAbilityDescriptions ={
    Mn: "Minimum damage ability does",
    Mx: "Maximum damage ability does",
    DoT: "Damage over time",
    DPS: "Damage per second",
    CD: "Damage from B.O.B's charge",
    ACD: "Damage from B.O.B's arm cannon",
    DH: "Damage from direct hit",
    S: "Splash damage",
    DPSMn:"Minimum damage per second ability does",
    DPSMx:"Maximum damage per second ability does",
    Inr:"Damage from inner ring of Doomfist's ultimate",
    OMn:"Minimum damage from outer ring of Doomfist's ultimate",
    OMx:"Maximum damage from outer ring of Doomfist's ultimate",
    SMn:"Minimum splash damage ability does",
    SMx:"Maximum splash damage ability does",
    Arw:"Damage from Dragonstrike's initial arrow",
    '1s':"From 0.2 to 1.0 seconds Deadeye does 100 damage per second, 80 Overall ",
    '2s':"From 1 to 1.5 seconds Deadeye does 275 damage per second, after 1.5 seconds it does 550 damage per second, 492.5 Overall ",
    '3s':"Deadeye does 550 damage per second past 1.5 seconds of being active, 1042.5 Overall",
    MnDPS:"Minimum damage per second ability does",
    MxDPS:"Maximum damage per second ability does",
    B:"Damage from bumping a target",
    P:"Damage from pinning a target",
    PreD:"Pre-detonation damage",
    Stick:"Damage from pulse bomb sticking to target",
    Jump:"Damage from Winston's initial jump",
    Imp:"Impact damage from Graviton Surge",
}

export default btnAbilityDescriptions;